# This file was autogenerated by scripts/init_gen.py
# It statically re-exports public classes defined in sibling modules.

from .decorators import auto_async_methods

__all__ = [
    'auto_async_methods',
]